name: Test

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

stages:
  - test

test:
  image: node:14.17.6-alpine3.14
  stage: test
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - node_modules/
  before_script:
    - yarn install
  script:
    - yarn test:ci
